version: "2"
services:
  pytimelapse:
    container_name: timelapse-live-view
    restart: unless-stopped
    image: ghcr.io/oxivanisher/timelapseliveview:master
    # build: .
    ports:
      - "${PUBLISH_PORT}:5000"
    environment:
      # create a .env file containing UPLOAD_KEY=something_secret
      UPLOAD_KEY: ${UPLOAD_KEY}
